{
  name: "string",
  artist: "string",
  title: "string",
  catalog_number: "string",
  eb_number: "string",
  google_drive_url: "string",
  customer: "string",
  in_hand_date: Date.now,
  units_ordered: "integer",
  sides: "integer",
  discs: "integer",
  format: "string",
  speed: "integer",
  matrix: "string",
  weight: "string",
  center_label: "string",
  jacket_type: "string",
  jacket_finish: "string",
  inner_sleeve_one: "string",
  inner_sleeve_one_finish: "string",
  insert_type: "string",
  insert_color: "string",
  insert_finish: "string",
  outerwear: "string",
  test_pressing_quantity: "integer",
  inner_sleeve_two: "string",
  inner_sleeve_two_finish: "string",
  disc_one_base_color: "string",
  barcode: "string",
  barcode_sticker: "string",
  download_cards: nil, # rubocop:disable Style/TrailingCommaInHashLiteral
}
